ingress:
  - https://tiltakspenger-saksbehandling.intern.dev.nav.no
  - https://tiltakspenger-saksbehandling.ansatt.dev.nav.no
replyURLs:
  - https://tiltakspenger-saksbehandling.ansatt.dev.nav.no/oauth2/callback
tenant: trygdeetaten.no
azure:
  groups:
    - name: ROLE_SAKSBEHANDLER
      id: 1b3a2c4d-d620-4fcf-a29b-a6cdadf29680
    - name: ROLE_BESLUTTER
      id: 79985315-b2de-40b8-a740-9510796993c6
    - name: ROLE_DRIFT
      id: c511113e-5b22-49e7-b9c4-eeb23b01f518
cluster: dev-gcp
envs:
  - name: TILTAKSPENGER_SAKSBEHANDLING_API_URL
    value: http://tiltakspenger-saksbehandling-api
  - name: AUTH_PROVIDER_URL
    value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
  - name: SAKSBEHANDLING_API_SCOPE
    value: api://dev-gcp.tpts.tiltakspenger-saksbehandling-api/.default
  - name: GOSYS_URL
    value: https://gosys-q2.dev.intern.nav.no/gosys
  - name: MODIA_PERSONOVERSIKT_URL
    value: https://modiapersonoversikt.intern.dev.nav.no/
replicas: 1
